import type { Metadata } from "next";
import { Righteous, Inter } from "next/font/google";
import "./globals.css";

const righteous = Righteous({
  variable: "--font-righteous",
  subsets: ["latin"],
  weight: "400",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap", 
});

export const metadata: Metadata = {
  title: "Case Closed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${righteous.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
